### ISSUE TITLE
"Sorry, this action is not available in simulation"

### ISSUE THREAD

**Issue by mandelbroo** [actions-on-google/assistant-conversation-testing-nodejs#2]
Not sure whether it's related to this library or not.
I'm getting `Sorry, this action is not available in simulation` response constantly after sending a trigger phrase.

I did set up a project on https://console.actions.google.com/ and able to test it from the Test tab and Google Home Mini as well.
For my integration testing, I've created a service account with Actions Viewer Role and imported a new secret key.

I'd appreciate any help.

<details>
<summary>Test output</summary>
  console.info
    Starting writePreview From Draft

      at ActionsOnGoogleTestManager.writePreviewFromDraft (node_modules/@assistant/conversation-testing/src/action-on-google-test-manager.ts:153:13)

  console.info
    writePreview From Draft completed

      at ActionsOnGoogleTestManager.writePreviewFromDraft (node_modules/@assistant/conversation-testing/src/action-on-google-test-manager.ts:155:13)

  console.info
    --- sendQuery called with 'Talk to My Test Project'

    at ActionsOnGoogleTestManager.sendQuery (node_modules/@assistant/conversation-testing/src/action-on-google-test-manager.ts:116:13)

 FAIL  handler/tests/e2e/welcome.spec.js (14.804 s)
  Test Suite
    ✕ trigger welcome (2047 ms)

  ● Test Suite › trigger welcome

    Expected value   undefined
    Received:
      null
    
    Message:
      Unexpected issue: Failed to find intent name in the response {"output":{"speech":[],"text":"Sorry, this action is not available in simulation","canvas":null,"actionsBuilderPrompt":null},"diagnostics":{"actionsBuilderEvents":[]},"conversationToken":""}: expected null to exist

    Difference:

      Comparing two different types of values. Expected undefined but received null.

      28 |     await test.sendQuery(TRIGGER_PHRASE);
      >29 |     test.assertIntent('actions.intent.MAIN');
</details>

**Comment by mandelbroo** [comment]
It was a dumb mistake with the invocation phrase :sweat_smile:
