### ISSUE TITLE
Firebase Terms of Service is not accepted. Navigate to your project's overview page on the Actions Console to accept the Terms of Service

### ISSUE THREAD

**Issue by panaC** [actions-on-google/assistant-conversation-testing-nodejs#4]
```
1) Test Suite
       "before all" hook: Before all setup for "trigger only test":
     Error: 9 FAILED_PRECONDITION: Firebase Terms of Service is not accepted. Navigate to your project's overview page on the Actions Console to accept the Terms of Service.
      at Object.callErrorFromStatus (node_modules/@grpc/grpc-js/build/src/call.js:31:26)
      at Object.onReceiveStatus (node_modules/@grpc/grpc-js/build/src/client.js:244:52)
      at Object.onReceiveStatus (node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
      at Object.onReceiveStatus (node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
      at /home/pierre/Documents/edrlab/audiobooks/audiobooks/test/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
      at processTicksAndRejections (internal/process/task_queues.js:75:11)

```

any idea how to solve this issue ?

```ts

import 'mocha';

import {ActionsOnGoogleTestManager} from '@assistant/conversation-testing';

const DEFAULT_LOCALE = 'en-US';
const DEFAULT_SURFACE = 'PHONE';

const PROJECT_ID = 'audiobooks-a';
const TRIGGER_PHRASE = 'Parler avec audiobooks';

describe('Test Suite', function () {
  // Set the timeout for each test run to 60s.
  this.timeout(60000);
  let testManager: ActionsOnGoogleTestManager;

  before('Before all setup', async () => {
    testManager = new ActionsOnGoogleTestManager({projectId: PROJECT_ID});
    await testManager.writePreviewFromDraft();
    testManager.setSuiteLocale(DEFAULT_LOCALE);
    testManager.setSuiteSurface(DEFAULT_SURFACE);
  });

  it('trigger only test', async () => {
    await testManager.sendQuery(TRIGGER_PHRASE);
    testManager.assertIntent('actions.intent.MAIN');
    // testManager.assertScene('Welcome');
    // testManager.assertSpeech('Welcome to Facts about Google!');
  });

  afterEach('post test cleans', async () => {
    testManager.cleanUpAfterTest();
  });
});

```

**Comment by mandelbroo** [comment]
Same issue

```
> env GOOGLE_APPLICATION_CREDENTIALS=./handler/tests/e2e/credentials.json jest --env=node --detectOpenHandles --globalSetup=./handler/tests/e2e/global-setup.js ./handler/tests/e2e/

Determining test suites to run...Starting writePreview From Draft
Error: 9 FAILED_PRECONDITION: Firebase Terms of Service is not accepted. Navigate to your project's overview page on the Actions Console to accept the Terms of Service.
    at Object.callErrorFromStatus (node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (node_modules/@grpc/grpc-js/build/src/client.js:244:52)
    at Object.onReceiveStatus (node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
    at Object.onReceiveStatus (node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
    at node_modules/@grpc/grpc-js/build/src/call-stream.js:130:78
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! google-assistant-actions-handler@0.1.0 test-e2e: `env GOOGLE_APPLICATION_CREDENTIALS=./handler/tests/e2e/credentials.json jest --env=node --detectOpenHandles --globalSetup=./handler/tests/e2e/global-setup.js ./handler/tests/e2e/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the google-assistant-actions-handler@0.1.0 test-e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     .npm/_logs/2021-03-09T10_12_31_000Z-debug.log
```

**Comment by leowilbur** [comment]
Hi @omohayui @mandelbroo @taycaldwell 
Could you help me to check this issue?
Thank you in advance

**Comment by omohayui** [comment]
I also got the same error when running the test.

And I have confirmed that the same error is returned when I request the [writePreview](https://developers.google.com/assistant/actions/api/reference/rest/v2/projects.preview/write) method in Actions API from the client library.
```sh
(node:16712) UnhandledPromiseRejectionWarning: Error: 9 FAILED_PRECONDITION: Firebase Terms of Service is not accepted. Navigate to your project's overview page on the Actions Console to accept the Terms of Service.
```

But no terms to accept are found in my Actions Console. Has anything changed inside Actions on Google?

**Comment by pglejzer** [comment]
did someone fix this problem?

**Comment by luca-nardelli-memori** [comment]
Same problem here

**Comment by omohayui** [comment]
I'm also still having the same problem and asking about it from GCP support cases.

**Comment by luca-nardelli-memori** [comment]
I contacted via mail some Google Developers Experts for Google Assistant

https://developers.google.com/assistant/community/gde

**Comment by pglejzer** [comment]
I think the problem is with writePreviewFromDraft()/ writePreviewFromVersion(). If I remove that part the tests are going and that error disappeared but it will fail from 'sendQuery' with the error ' Error: sendInteraction API call failed: Error: 3 INVALID_ARGUMENT: Interaction did not trigger the preview of an action.'.

**Comment by yoichiro** [comment]
Hi there! I'm one of Assistant GDEs. Luca, thank you for the report, we got your email. I have already reported this issue to the team of Google, and I heard that they're investigating about it. I intend to post a comment here after receiving the feedback from the team.

**Comment by pglejzer** [comment]
I think it is working now. My tests passed. @yoichiro Thanks!

**Comment by omohayui** [comment]
I also confirmed it has fixed! Thanks a lot!

**Comment by leowilbur** [comment]
It is working. Thank you in advance :)
Great job

**Comment by atulep** [comment]
Hi everyone,

Thank you for reporting this. We rolled out a fix for this issue, and it should be working now.

I'm closing this issue, but feel free to reopen should the issue come up again.

**Comment by panaC** [comment]
thanks everyone :+1:

**Comment by luca-nardelli-memori** [comment]
Thanks a lot!!!

**Comment by luca-nardelli-memori** [comment]
The problem is here again !!

Error: 9 FAILED_PRECONDITION: Firebase Terms of Service is not accepted. Navigate to your project's overview page on the Actions Console to accept the Terms of Service.

@atulep

**Comment by omohayui** [comment]
Are you still having the error? I can't get the error now.

**Comment by luca-nardelli-memori** [comment]
I confirm I still have the error @omohayui

**Comment by luca-nardelli-memori** [comment]
> Hi everyone,
> 
> Thank you for reporting this. We rolled out a fix for this issue, and it should be working now.
> 
> I'm closing this issue, but feel free to reopen should the issue come up again.

Hello, the problem is still here..

**Comment by atulep** [comment]
Hello, 

Thanks for reporting this. We did some changes to the API; however, e2e testing went fine, and I can't reproduce this issue now too. 

Did you use the same setup & code as in https://github.com/actions-on-google/assistant-conversation-testing-nodejs/issues/4#issue-820519888? Also, does it also fail after:

```
Determining test suites to run...
Starting writePreview From Draft
```
?

**Comment by luca-nardelli-memori** [comment]
> Did you use the same setup & code as in [#4 (comment)](https://github.com/actions-on-google/assistant-conversation-testing-nodejs/issues/4#issue-820519888)? Also, does it also fail after:

To be honest I'm using this project: https://github.com/actions-on-google/assistant-conversation-nodejs

20 days ago, when the problem was resolved here, it was resolved also in the project "assistant-conversation-nodejs"

**Comment by luca-nardelli-memori** [comment]
@atulep could you please tell me which changes did you make to the API, so I can propose pull request in the assistant-conversation-nodejs project ?

**Comment by atulep** [comment]
> > Did you use the same setup & code as in [#4 (comment)](https://github.com/actions-on-google/assistant-conversation-testing-nodejs/issues/4#issue-820519888)? Also, does it also fail after:
> 
> To be honest I'm using this project: https://github.com/actions-on-google/assistant-conversation-nodejs
> 
> 20 days ago, when the problem was resolved here, it was resolved also in the project "assistant-conversation-nodejs"

If you still experience this error, can you go to the Actions on Google Console and try to accept Terms of Service?

> @atulep could you please tell me which changes did you make to the API, so I can propose pull request in the assistant-conversation-nodejs project ?

The change didn't affect the frontend of the API. Sorry for confusion.

**Comment by luca-nardelli-memori** [comment]
> can you go to the Actions on Google Console and try to accept Terms of Service?

Unfortunately no, because  there is not a checkbox where to accept the terms :-(

 > The change didn't affect the frontend of the API. Sorry for confusion.

Ok, so the fix was applied to the backend ?

**Comment by atulep** [comment]
Apologies for delayed reply.

> > can you go to the Actions on Google Console and try to accept Terms of Service?
> 
> Unfortunately no, because there is not a checkbox where to accept the terms :-(

Hm, this doesn't sound right. Can you please describe your setup?

> > The change didn't affect the frontend of the API. Sorry for confusion.
> 
> Ok, so the fix was applied to the backend ?

Yes.

**Comment by luca-nardelli-memori** [comment]
> Can you please describe your setup?

There is not any checkbox where to accept the requested terms...I searched everywhere

**Comment by mishushakov** [comment]
I'm having the issue but with `@assistant/actions` package
https://github.com/actions-on-google/assistant-actions-nodejs/issues/2
