### ISSUE TITLE
writePreviewFromDraft hangs and then results in an internal error

### ISSUE THREAD

**Issue by davidvc** [actions-on-google/assistant-conversation-testing-nodejs#9]
writePreviewFromDraft is timing out. And then if I set timeout to a very long time I get this error after about 30 seconds. My suspicion is that the GRPC request is timing out and the network connection is dropped. But anyway it never works.

Project id: venus-c8f37

```
Starting writePreview From Draft
VError: a BeforeAll hook errored, process exiting: test/acceptance/features/support/hooks.js:25: 13 INTERNAL: Internal error encountered.
    at /Users/dvc/venus/venus-google-action/node_modules/@cucumber/cucumber/lib/runtime/index.js:64:23
caused by: Error: 13 INTERNAL: Internal error encountered.
    at Object.callErrorFromStatus (/Users/dvc/venus/venus-google-action/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/Users/dvc/venus/venus-google-action/node_modules/@grpc/grpc-js/build/src/client.js:244:52)
    at Object.onReceiveStatus (/Users/dvc/venus/venus-google-action/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
    at Object.onReceiveStatus (/Users/dvc/venus/venus-google-action/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
    at /Users/dvc/venus/venus-google-action/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

**Comment by davidvc** [comment]
Note that when I use the developer UI and select the Test tab, it takes a good three minutes for the Preview to be updated.

**Comment by Fleker** [comment]
If you update via the web console, are you able to test from the current version?

**Comment by davidvc** [comment]
Hi, sorry I didn't get notified of your update! 

Yes I had to update from the web console. Now it works every time. I'll close this.
